version: "3.4"

services:

  nginx:
    image: eduardoshanahan/nginx:latest
    container_name: es_nginx
    ports:
      - target: 80
        published: 8080
    volumes:
      - type: bind
        source: ./content
        target: /usr/share/nginx/html
        read_only: true
    command:
      - nginx
      - "-g"
      - "daemon off;"
