version: "3"

services:

  nginx:
    image: eduardoshanahan/nginx:latest
    container_name: es_nginx
    ports:
      - 8080:80
    volumes:
      - ./content:/usr/share/nginx/html:ro
    command:
      - nginx
      - '-g'
      - 'daemon off;'
